version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME_DEVELOPMENT}"
    container_name: iap
    volumes:
      - ./postgres:/var/lib/postgresql/data
